### ISSUE TITLE
Soundcloud - Artist name missing.

### ISSUE THREAD

**Issue by lolaontwitch** [PacoHobi/CurrentSong#1]
I have set up the extension on Firefox and OBS correctly (I think), including the tags that are shown in the extension itself. 

The song name loads, but the artist's name does not. I have tried several different artists to make sure, but only the song title is showing up on OBS.

**Comment by PacoHobi** [comment]
As far I can see SoundCloud only provides a track name. The track name sometimes contains the artists and sometimes it doesn't, and if it does it isn't in a consistent format. E.g:

. | Track name | Format
---|--------------|----------
1 | WAITING TOO LONG - HIPPIE SABOTAGE | song - artist
2 | Jaymes Young - I'll Be Good (Thero Remix) | artist - song
3 | In Quiet Rooms | song
4 | N°090 - Relaxing Piano Music - inspiring, dreamy, easy | ?
5 | 'Dawn' Pt.2 (An Ambient Mix) | song?

It seems that the majority of tracks use the `artist - song` format, I could use that to try to get an artist name, but that would inevitably lead to problems, for example in the case where the format is `song-artist` (see examples 1 and 4).

I don't personally use SoundCloud, so maybe I'm missing something, if I am please tell me. If not, if you want I could add an option in the next update that would try to extract the artist name, but that would get it wrong if the track contains a `-` and doesn't follow the `artist - song` format.

**Comment by lolaontwitch** [comment]
Thank you for the reply! 

I understand that it could lead to problems. If it's a simple fix, I would be happy, but if not, then I completely understand if it stays the way it is. For now, I'll just have to add the artist in another text box or something.

Your extension is probably the best that I've tried to work with so far and I'll most definitely continue to use it, regardless.

**Comment by PacoHobi** [comment]
It's a simple fix. I'll add it as an option in the preferences for the next update.

**Comment by PacoHobi** [comment]
Added feature on [CurrentSong v0.2.1](https://github.com/PacoHobi/CurrentSong/releases/tag/v0.2.1) @lolaontwitch
