### ISSUE TITLE
Folder Error

### ISSUE THREAD

**Issue by NeumiNic** [PacoHobi/CurrentSong#10]
Hi bro, I have problem with your Plug-In - On settings I select my folder, but all time it write the same error : 
![snimek obrazovky 25](https://cloud.githubusercontent.com/assets/16310173/11819878/84ee5342-a362-11e5-9923-f869c74a8782.png)

Can you help me? :) Thank you.

**Comment by ceco22** [comment]
I have the same problem with this.. I create the folder but there is no text for my plugin

**Comment by PacoHobi** [comment]
Sorry, I completely forgot about this issue.

Once you select the desired folder in CurrentSong's options, does its path appear next to the "Browse ..." button like shown in this image?

![firefox_2016-02-15_18-25-25](https://cloud.githubusercontent.com/assets/5880993/13057185/5fcdb9aa-d412-11e5-96f0-90933e484156.png)


If so, is the path still there after restarting Firefox?

**Comment by PacoHobi** [comment]
If you are experiencing this problem, please contact me here and I will try to resolve it. Right now I'm missing information to know what is causing the problem.

**Comment by ceco22** [comment]
I ve fix this with restart my PC... After that I set the folder without problem. Is there any chance that this plugin will support direct file to CLR Browser for OBS or Browser Plugin for OBS Studio ? My problem is with size of song name. When song name is large I can't keep it under text box..

**Comment by PacoHobi** [comment]
CurrentSong does support CLR Browser and Browser plugin, that's why CurrentSong also saves a XML file. Of course the HTML page to show with the plugin is missing, I supposed users wanted to do that themselves.

I might do a simple HTML page so that users can use it as a template for their own pages.

**Comment by PacoHobi** [comment]
@ceco22 check out [this HTML page](https://github.com/PacoHobi/CurrentSong/blob/master/html_views/song.html). It's very crude, but it should get you started to display the song info with the Browser plugin.

![anim](https://cloud.githubusercontent.com/assets/5880993/13644383/db0738d8-e625-11e5-89d1-b28fe9e1cf7e.gif)

**Comment by PacoHobi** [comment]
I'm going to close this issue.

@ceco22 if you still want to talk about the Browser plugin please open a new issue, as it is a different topic.
