### ISSUE TITLE
This add-on could not be installed because it has not been verified.

### ISSUE THREAD

**Issue by BenVlodgi** [PacoHobi/CurrentSong#11]
When I attempt to import the add-on into firefox I get this message 
> This add-on could not be installed because it has not been verified.

I haven't found a way to circumvent this.
Using Firefox 43.0.1

**Comment by PacoHobi** [comment]
Try to install it from the Firefox Addons site:

https://addons.mozilla.org/en-US/firefox/addon/currentsong/

**Comment by BenVlodgi** [comment]
Perfect, thanks!

**Comment by PacoHobi** [comment]
:+1:
