### ISSUE TITLE
Files are not being written

### ISSUE THREAD

**Issue by Hengplank** [PacoHobi/CurrentSong#12]
Choosing a specified folder path anywhere does not work. there is no file being written or parsed out on any website(pandora, youtube, etc.)

**Comment by PacoHobi** [comment]
You are not the first to have this problem, but I haven't heard back from the other people and therefore I haven't been able to figure it out. Let's start with this two questions and see if we can find the problem.

__1.__ Once you select the desired folder in CurrentSong's options, does its path appear next to the "Browse ..." button like shown in this image?

![](https://cloud.githubusercontent.com/assets/5880993/13057185/5fcdb9aa-d412-11e5-96f0-90933e484156.png)


__2.__ When you go to a YouTube video (a video, not just the YouTube page), does an alert window like the one in the following image appear?

![alert](https://cloud.githubusercontent.com/assets/5880993/13582236/815cc6de-e4ab-11e5-98ec-77ef8ee1e14c.png)

**Comment by Hengplank** [comment]
No alerts. The browse button is there, and I have set and tested different
folders.

**Comment by PacoHobi** [comment]
But when you click Browse and then select a folder, does the path to the folder appear next to the Browse button (the part marked with red in the image above)?

**Comment by Hengplank** [comment]
Yes.

**Comment by PacoHobi** [comment]
Ok, go to CurrentSong's options and enable the Notifications option. Now go to a YouTube video, does a desktop notification appear?

If you could also tell me watch operating system you use and your Firefox version.

**Comment by Hengplank** [comment]
I am using Windows 10 Pro x64bit. There is no notification when that option
is ticked. By the way I apologise for calling your app a rip-off. I
appreciate the troubleshooting and the well mannered responses.

**Comment by Hengplank** [comment]
Firefox is most updated version.

**Comment by PacoHobi** [comment]
I'm working on a version with debug messages. Tomorrow I will upload it and hopefully when you run it and give me the debug messages I will see in what part of the code the problem is.

**Comment by PacoHobi** [comment]
Here is the debug version: [debug.xpi.zip](https://github.com/PacoHobi/CurrentSong/files/163452/debug.xpi.zip).

Please download this version and follow the steps in the following video, then post here the resulting debug messages.

https://www.youtube.com/watch?v=cI9YGuFFI_Q

**Comment by Hengplank** [comment]
It seems to work on my other laptop that I tested that on. There are no
generated log on my desktop computer. But I have solved the issue by
reinstalling Firefox. It must be some settings with Firefox
rerouting/history/cookies modifying that I've done(computer science
networking coding). Cheers for the help, and I highly appreciate the
debugging. =D

**Comment by PacoHobi** [comment]
That's great. I now know to suggest a Firefox reinstall for this type of issues. 

If you have any other issue or suggestion, please open an issue or shoot me an email :+1:
