### ISSUE TITLE
CurrentSong isn't working at all

### ISSUE THREAD

**Issue by 47b3n** [PacoHobi/CurrentSong#13]
### Expected behaviour
The song name and other info has to be placed in PATH/song.txt

### Actual behaviour
The file isn't created.

How do I actually save my settings in Addons?

### Details
**Operating system:** Window 7
**Firefox version:** 42.0

#### EDIT I UPDATED FIREFOX AND FIXED IT

**Comment by PacoHobi** [comment]
Glad it works for you know. Hope you like it. If you run into any other problems or have any suggestion or idea open an issue or send me an email :+1:
