### ISSUE TITLE
Current song and 8tracks. Only displays first song

### ISSUE THREAD

**Issue by hkezza** [PacoHobi/CurrentSong#14]
### Expected behaviour
Displays song names on 8tracks.

### Actual behaviour
Displays only the first song on 8tracks, but not the rest of the other songs.  This only happens in 8tracks and not on Youtube or Pandora.

### Details
**Operating system:**  Mac 10.11
**Firefox version:** 45.0

**Comment by PacoHobi** [comment]
Fixed it with version 1.2.7. It's currently in process of being approved in the Firefox add-ons platform.

You can wait until the update is fully approved, or install it now from here:

https://addons.mozilla.org/firefox/downloads/file/410948/currentsong-1.2.7-fx.xpi

:+1:

**Comment by PacoHobi** [comment]
Version 1.2.7 is now approved and you can download it from here:

https://addons.mozilla.org/es/firefox/addon/currentsong/
