### ISSUE TITLE
Soundcloud only gives the title of the song, not the artist

### ISSUE THREAD

**Issue by NeroChaos1** [PacoHobi/CurrentSong#15]
### Expected behaviour
Set up the Current Song add-on, with (or without, I tried both) "parse titles" checked and the appropriate formatting applied. Listening on Soundcloud should give the song title and artist name. Like: %song% by %artist%

### Actual behaviour
Trying to use it with Soundcloud only yields a %song% by [blank], instead of %song% by %artist%

### Steps to reproduce the behaviour
I tried switching to my playlist, or to a station to see if that was the issue. No matter what, it seems Current Song won't return the artist name and will just give the song title.

### Details
**Operating system: Windows 10 Pro** 
**Firefox version: 45.0.1**

**Comment by PacoHobi** [comment]
That actually was the actual behaviour for SoundCloud: it would only get the artist correctly if:
+ The _Parse Title_ option was on
+ The artist was included in the song title
+ The song title was in the format `artist - song`.

The reason for that is that the artist name doesn't appear in the player SoundCloud has at the bottom of the page.

I made an improvement and now the artist name is extracted from the title of the page. The correct behaviour for SoundCloud is included in CurrentSong v1.2.8, that is now being reviewed in the Firefox add-ons platform. I will post another message here when the new version is approved and is ready to be installed.

Thanks for the suggestion.

**Comment by PacoHobi** [comment]
Version 1.2.8 is now available from here:

https://addons.mozilla.org/es/firefox/addon/currentsong/
