### ISSUE TITLE
Doesn't not work after disabling history

### ISSUE THREAD

**Issue by Te-Ata** [PacoHobi/CurrentSong#16]
### Expected behaviour
Write song in txt files

### Actual behaviour
Didn't do anything, does not create text files after deeleting it. Everything since I disable past history

### Details
Since past history is disable

**Operating system:** 
Windows 10

**Firefox version:** 
47.0.1

**Comment by PacoHobi** [comment]
I was able to replicate it. If it's set to _Never remember history_ it doesn't work, and if you set it to _Remember history_ it works again.

One solution that worked for me is setting _Use custom settings for history_, and with the options set as restrictive as possible, CurrentSong still worked.

Hope this works for you.

![screen shot 2016-07-24 at 14 33 10](https://cloud.githubusercontent.com/assets/5880993/17083846/cd8adcd0-51ac-11e6-83f4-408e0bd8cbf8.png)

![screen shot 2016-07-24 at 14 41 41](https://cloud.githubusercontent.com/assets/5880993/17083847/d1c24a2c-51ac-11e6-8f89-eaaa9f6a2238.png)

**Comment by Te-Ata** [comment]
Hey thanks for that quick reply ! I really appreciate it :)

Your solution is working ! It's awesome ! You did a really good job with
that plugin !

wish you the best, best regards

2016-07-24 14:49 GMT+02:00 Paco Hobi <notifications@github.com>:

**Comment by PacoHobi** [comment]
👍
