### ISSUE TITLE
Nightbot/Pandora switching

### ISSUE THREAD

**Issue by veekdot** [PacoHobi/CurrentSong#19]
Title is a bit misleading. I don't think the problem has anything to do with the combination of the services I'm using.

### Expected behaviour
Would like to seamlessly switch between Pandora & Nightbot AutoDJ/Songrequest

### Actual behaviour
Nightbot does not work. Pandora works just fine though ;)

### Steps to reproduce the behaviour
The behaviour is consistent. I tried disabling all my addons to ensure there were no issues with that with no effect. Are there special steps required to make nightbot work with CurrentSong?

### Details
**Operating system:** 
Win10 Build 1511
**Firefox version:** 
50.2 with CurrentSong 1.3.2

>>>Suggestion
As a suggestion I'd also like to customize the names of the files, generated by CurrentSong.

**Comment by PacoHobi** [comment]
I'm quite busy, I hope to be able to take a look this weekend.

**Comment by PacoHobi** [comment]
If you don't open Pandora and just open Nightbot it still doesn't work, right?

**Comment by veekdot** [comment]
Just tried it again to be sure. And yeah, Nightbot Songs dont get written to the song.txt

Thank you for your time, take all of it you need.

**Comment by PacoHobi** [comment]
Where you using the beta of nightbot? If so it will be fixed on next release.

**Comment by PacoHobi** [comment]
@veekdot this is solved in [version 1.3.3](https://addons.mozilla.org/firefox/addon/currentsong/).
