### ISSUE TITLE
1st letter of the song title is missing when using it for youtube

### ISSUE THREAD

**Issue by Autisticgaming** [PacoHobi/CurrentSong#2]
Is this a known error / problem?

The 1st letter is missing of the song title in the text file.

**Comment by PacoHobi** [comment]
I'm not able to recreate what you are saying. Can you give me the URL of a video where this is happening?

**Comment by Autisticgaming** [comment]
I am using plug.tv which uses youtube videos, so there shouldn't be a problem with the extension?

**Comment by PacoHobi** [comment]
Ok, the bug was with the site `plug.dj` and not `youtube.com`. I found and fixed the bug, update to [version v0.2.2](https://github.com/PacoHobi/CurrentSong/releases/latest) to get the fix.

Thank you for using CurrentSong, if you have any other issue or suggestion feel free to contact me :+1:

**Comment by Autisticgaming** [comment]
Thank you for your super quick help!
