### ISSUE TITLE
Multip line not parsed

### ISSUE THREAD

**Issue by Fu2chN** [PacoHobi/CurrentSong#20]
Hi, I would have liked to be able to make several line breaks (%song%%line%%artist%%line%%album%).
Thx for your extention.

### Expected behaviour
%line% Add a new line to each use

### Actual behaviour
%line% added once a line break, the following is not considered.

### Steps to reproduce the behaviour
Add multipe %line% and the first %line% work the second not parsed.

### Details
**Operating system:** 
Windows 10 Pro 64-bit (10.0, Build 14393)
**Firefox version:**
Firefox 50.1.0
CurrentSong 1.3.2

**Comment by PacoHobi** [comment]
I'll check it out along this week.

**Comment by PacoHobi** [comment]
@Fu2chN this is solved in [version 1.3.3](https://addons.mozilla.org/firefox/addon/currentsong/). Thanks for letting me know.
