### ISSUE TITLE
Don't work with vk.com and Nightbot.

### ISSUE THREAD

**Issue by bluriwe** [PacoHobi/CurrentSong#3]
Hello. As I wrote will not work with vk.com and bot.
I would like to have a function like !music in chat Twitchy , and the bot to give information about the music that is playing right now.
![134](https://cloud.githubusercontent.com/assets/12100578/7320645/b560eb54-eabf-11e4-838e-a9cc9d2a0028.PNG)

**Comment by PacoHobi** [comment]
I changed my vk.com to Russian and it still works for me.

So the first possibility I see is that you don't have the extension up to date, support for vk.com was added on version v0.2.0. So check that you have version v0.2.x.

![vk](https://cloud.githubusercontent.com/assets/5880993/7322258/e29230ba-ea74-11e4-89bd-cbc8cf69ff66.png)

**Comment by bluriwe** [comment]
Yep. Today my firefox updated on 0.22. And all work. thx for info 

24.04.2015, 18:28, "Paco Hobi" <notifications@github.com>:

**Comment by PacoHobi** [comment]
Thank you for using CurrentSong, if you have any other issue or suggestion feel free to contact me :+1:
