### ISSUE TITLE
Not working on Soundcloud

### ISSUE THREAD

**Issue by RCHZ** [PacoHobi/CurrentSong#32]
I installed this plugin last night and was able to get it to work with OBS while listening to Soundcloud. Hours later, after shutting down and restarting.... it is no longer saving info to my text file. I jumped on YouTube to see if that works and it worked just fine. So it seems to be working, but not on Soundcloud. I've tried disabling it and enabling again, multiple times. I've also restarted Firefox, cleared out the info in text file and rebooted my laptop. Did Soundcloud change something possibly? 

*UPDATE*
It's sorta working now. %song% is not being saved to the text file though. I also noticed that if I play tracks from a playlist, it doesn't work at all.

I'm using Firefox v53.0.3 and CurrentSong v1.3.5

Streaming with OBS v19.0.2, displaying CurrentSong through the text file.

**Comment by PacoHobi** [comment]
Hi @RCHZ, looks like SoundCloud changed something. What's strange is it works for you for some songs. Could you please give me a link where it works and one that doesn't work, and what does and doesn't work with each link?

**Comment by RCHZ** [comment]
This is the format I have entered in options: %song%%line%by %artist% 
When I play tracks from search or user profiles, the only info being sent to the text file is %line%by %artist%. If a track is played from a playlist, no information is sent to the text file.

You can try this on any user profile who has stand alone tracks and tracks in a playlist or try it out on mine here: https://soundcloud.com/rchz

First try to play a song from the playlist, which should be listed first since I just made it. I tried clicking play from the tracks inside the playlist instead of the big play button, but that didn't help. The info still is not being transferred to the text file.

Next click one of my individual tracks and you should see that only %line%by %artist% is being transferred to the text file.

I'm new to live streams and I love this plugin, hope you can get it figured out! Thanks for the reply.

**Comment by Virtuitous** [comment]
RCHZ is correct, 
I only use %artist%
It works 100% when listening to song, 
and 0% when listening to playlist.

However, I don't understand how the abovementioned workaround helps..?

**Comment by PacoHobi** [comment]
@RCHZ @Virtuitous soundcloud should work in v1.3.6 which you can download now. Sorry for the delay guys 😞
