### ISSUE TITLE
play.spotify.com to player.spotify.com

### ISSUE THREAD

**Issue by ColbyC** [PacoHobi/CurrentSong#4]
Spotify now redirects 'play' subdomain to 'player'

**Comment by PacoHobi** [comment]
For me if I go to play.spotify.com it's stays in that subdomain. If I go to player.spotify.com it redirects me to play.spotify.com.

So just to make sure, when you go to play.spotify.com it redirects you to player.spotify.com? If so, does the page still look the same as before?

I suppose it's something country dependent? If you don't mind can you tell me your OS and country? (So maybe I can find a VPN and try it).

**Comment by ColbyC** [comment]
I am on win7 in the usa

**Comment by PacoHobi** [comment]
Sorry for the delay (have been busy with college). I'm not able to replicate your problem, but I tried something that I hope that fixes the issue.

Download this version of the add-on, and if it fixes it I will publish it as a official update:
https://dl.dropboxusercontent.com/u/1404483/currentsong.xpi

Again, sorry for the long wait.

**Comment by PacoHobi** [comment]
I have included the fix with release [v0.2.7](https://github.com/PacoHobi/CurrentSong/releases/tag/v0.2.7).
