### ISSUE TITLE
Spotify web player not working

### ISSUE THREAD

**Issue by macht** [PacoHobi/CurrentSong#6]
For spotify: document.getElementById("app-player") kicks back undefined. Maybe it was recently changed? I was able to extract the current song title and artist with the following:
```
song = document.getElementById("main").contentWindow.document.getElementById("miniplayer").getElementsByClassName("title")[0].textContent

artist = document.getElementById("main").contentWindow.document.getElementById("miniplayer").getElementsByClassName("artist")[0].textContent
```
Note that I am **not** a JS developer—I only discovered this by stumbling around the DOM properties window. There's almost definitely a better way to extract this—I just hope I've pointed you in the right direction.

**Comment by PacoHobi** [comment]
I suppose when you use Spotify your URL is `player.spotify.com`. It seems like this is a beta player (default is `play.spotify.com`), the problem is I can't access it because when I try to go to `player.spotify.com` it redirects me to `play.spotify.com`.

I'll try to fix it whit the info you gave me. Would you be able to try the fix before I publish the update to make sure that it works?

I hope to have a fix later today, many thanks for the helpful information.

**Comment by PacoHobi** [comment]
`#miniplayer` is an iframe right? Could you paste all the inner HTML of that iframe?

If it is much code you can use [GitHub Gists](https://gist.github.com) or [PasteBin](http://pastebin.com).

**Comment by macht** [comment]
Yeah, play.spotify.com redirects me to player.spotify.com.

`#miniplayer` appears to be a div inside `#main`, which is an iframe. Here's the inner HTML:
```html
<div id="miniplayer" data-bind="with: miniplayer">
        <div style="background-image: url(&quot;undefined&quot;);" class="miniplayer-bg" data-bind="style: { backgroundImage: artistImageCSS }"></div>
        <div class="cover">
          <figure style="background-image: url(&quot;https://d3rt1990lpmkn.cloudfront.net/unbranded/703681205f5cb47ee76856ecc34d34925fb7a9ab&quot;);" data-bind="style: { backgroundImage: coverCSS }"></figure>
        </div>
        <div class="metadata">
          <div>
            <h4 class="title" data-bind="text: trackName">The Parting Glass</h4>
            <h5 class="artist" data-bind="text: trackArtists">Peter Hollens</h5>
          </div>
        </div>
        <div class="expand"></div>
      </div>
        <div style="background-image: url(&quot;undefined&quot;);" class="miniplayer-bg" data-bind="style: { backgroundImage: artistImageCSS }"></div>
        <div class="cover">
          <figure style="background-image: url(&quot;https://...;);" data-bind="style: { backgroundImage: coverCSS }"></figure>
        </div>
        <div class="metadata">
          <div>
            <h4 class="title" data-bind="text: trackName">The Parting Glass</h4>
            <h5 class="artist" data-bind="text: trackArtists">Peter Hollens</h5>
          </div>
        </div>
        <div class="expand"></div>
```
I hope this helps.

**Comment by PacoHobi** [comment]
Really helpful. I implemented a fix, could you try this version and see if the title, artist and cover is saving correctly?

https://dl.dropboxusercontent.com/u/1404483/currentsong.xpi

**Comment by macht** [comment]
Looks like it's working great!

**Comment by PacoHobi** [comment]
Fantastic! Thank you very much fore the help @macht.

Thank you for using CurrentSong, consider leaving a rating on the [OBS page](https://obsproject.com/forum/resources/currentsong.182/) and/or on [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/currentsong/). If you have any other issue or suggestion feel free to contact me :+1:
