### ISSUE TITLE
Feature: Make image transparent when not available

### ISSUE THREAD

**Issue by green-big-frog** [PacoHobi/CurrentSong#8]
Thanks for your great tool!

It would be great if the image would be replaced by a transparent one if you close Firefox or there is no image available. This would require switching from .jpg to .png!

It would be great if you could consider implenting this!

**Comment by PacoHobi** [comment]
That's actually a great idea, this way in OBS you can put your own customized "no-artwork" image behind the actual artwork image, and if CurrentSong doesn't find artwork you can see your own customized no-artwork.

The thing is that all this sites have the artwork in JPG format, so CurrentSong's no-artwork image must also be JPG. Therefore I replaced the artwork by a single black pixel.

Have a look if this works for you, no new update needed, should work right now. Thanks for the feedback.

**Comment by green-big-frog** [comment]
Thanks for your quick reply! Is it maybe possible that you did forget to push to github or update the firefox plugin? no changes...

**Comment by PacoHobi** [comment]
There is no update to the add-on, just changed the image on the host.

**Comment by green-big-frog** [comment]
Ok...

Can you give me a way of reproducing what you changed?

I think we might be talking past each other...

**Comment by PacoHobi** [comment]
Ok if you use CurrentSong with a YouTube video (for which CurrentSong does not download artwork) you should have the following `song.jpg` file (http://pacohobi.com/currentsong/artworkw.jpg). which is a single black pixel (closest to a transparent image in JPG format).

The addon downloads the image at that URL when the page does not have artwork support. If you are still seeing the old image when visiting that URL your browser must have the old one cached, try reloading a few times or closing and reopening the browser.

**Comment by green-big-frog** [comment]
Ok... I know understand what you meant!

So now only changing the picture to the black pixel when there isn't any music being played, f.e. firefox or the tab gets closed, the music is paused, etc. has to be added...

**Comment by PacoHobi** [comment]
I don't believe I can do that, but I will look into that.
