### ISSUE TITLE
Get %artist% and %album% from URL (soundcloud)

### ISSUE THREAD

**Issue by green-big-frog** [PacoHobi/CurrentSong#9]
Currently CurrentSong only (can) grabs the title of the playing song at soundcloud.

Wouldn't it be possible to grab the author and Album (set) from the URL?

Example:
    https://soundcloud.com/approachingnirvana/sets/not-even-once

    "approachingnirvana" = %artist%
    "not-even-once" = %album%

**Comment by PacoHobi** [comment]
You can play a song without being on that songs page, but it look like the URL you provide is embedded in the mini player at the bottom, so the information could be extracted from there.

Also "approachingnirvana", looks like a user ID, not a display name, therefore it doesnt include spaces or special characters, and can be even completly different to the display name. For example https://soundcloud.com/roywoodsofficial/drama-feat-drake:

```
"roywoodsofficial" = %artist%
"drama-feat-drake" = %album%
```

Whereas the actual display name is "Roy Wood$".

But I just noticed that when a song is playing the page title contains the formatted song and artist name, I will look into extracting that info from the page title.

Thanks for the feedback and suggestions.

**Comment by PacoHobi** [comment]
Added artist name for SongCloud in CurrentSong v1.2.8. Check out #15.

**Comment by green-big-frog** [comment]
awesome!
